#!/usr/bin/env python

Import("host_env")

AlwaysBuild(host_env.StaticObject(target="bootsector.bin", source="bootsector.asm"))

AlwaysBuild(host_env.StaticObject(target="bootloader.bin", source="bootloader.asm"))
